### ISSUE TITLE
error unicode data

### ISSUE THREAD

**Issue by saria85** [hugochan/KATE#8]
I am trying to run on 20news group which I got this error:

Traceback (most recent call last):
  File "construct_20news.py", line 30, in <module>
    main()
  File "construct_20news.py", line 23, in main
    train_corpus, test_corpus = construct_train_test_corpus(args.train_path, args.test_path, args.out_dir, threshold=args.threshold, topn=args.topn)
  File "/home/saria/Downloads/KATE-master/autoencoder/preprocessing/preprocessing.py", line 167, in construct_train_test_corpus
    train_docs, vocab_dict, train_word_freq = construct_corpus(train_path, True, threshold=threshold, topn=topn, recursive=True)
  File "/home/saria/Downloads/KATE-master/autoencoder/preprocessing/preprocessing.py", line 120, in construct_corpus
    word_freq, doc_word_freq = load_data(corpus_path, recursive)
  File "/home/saria/Downloads/KATE-master/autoencoder/preprocessing/preprocessing.py", line 112, in load_data
    raise e
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf3 in position 426: invalid continuation byte

Thanks

**Comment by hugochan** [comment]
Please refer to this: https://github.com/hugochan/KATE/issues/2

**Comment by saria85** [comment]
sorry but that not clear to me. what does it mean by 'cash' is not in your vocab?

**Comment by hugochan** [comment]
To avoid the issue, replace [this line](https://github.com/hugochan/KATE/blob/master/autoencoder/preprocessing/preprocessing.py#L94) with the following: with codecs.open(filename, 'r', encoding='UTF-8', errors='ignore') as fp

**Comment by saria85** [comment]
Thanks, 
I just need to see the result early then detail on that, so in that case, I know how it can help with my research.

This is what I am running (I know my testing and training dataset is the same I just want to get it run at this moment)

python construct_20news.py -train [/home/saria/Downloads/datasets/20_newsgroups] -test [/home/saria/Downloads/datasets/20_newsgroups] -o [/home/saria/Downloads/datasets] -threshold 5 -topn 100

and I got this,

File "construct_20news.py", line 30, in <module>
    main()
  File "construct_20news.py", line 23, in main
    train_corpus, test_corpus = construct_train_test_corpus(args.train_path, args.test_path, args.out_dir, threshold=args.threshold, topn=args.topn)
  File "/home/saria/Downloads/KATE-master/autoencoder/preprocessing/preprocessing.py", line 167, in construct_train_test_corpus
    train_docs, vocab_dict, train_word_freq = construct_corpus(train_path, True, threshold=threshold, topn=topn, recursive=True)
  File "/home/saria/Downloads/KATE-master/autoencoder/preprocessing/preprocessing.py", line 122, in construct_corpus
    vocab_dict = build_vocab(word_freq, threshold=threshold, topn=topn)
  File "/home/saria/Downloads/KATE-master/autoencoder/preprocessing/preprocessing.py", line 154, in build_vocab
    word_freq = zip(*word_freq[:topn])[0]
IndexError: list index out of range

**Comment by hugochan** [comment]
In your case, please try this: python construct_20news.py -train /home/saria/Downloads/datasets/20_newsgroups -test /home/saria/Downloads/datasets/20_newsgroups -o /home/saria/Downloads/datasets -threshold 5 -topn 100

**Comment by saria85** [comment]
thanks for following up with me.
but when I use like this I will get invalid argument....

Traceback (most recent call last):
  File "construct_20news.py", line 30, in <module>
    main()
  File "construct_20news.py", line 23, in main
    train_corpus, test_corpus = construct_train_test_corpus(args.train_path, args.test_path, args.out_dir, threshold=args.threshold, topn=args.topn)
  File "/home/saria/Downloads/KATE-master/autoencoder/preprocessing/preprocessing.py", line 167, in construct_train_test_corpus
    train_docs, vocab_dict, train_word_freq = construct_corpus(train_path, True, threshold=threshold, topn=topn, recursive=True)
  File "/home/saria/Downloads/KATE-master/autoencoder/preprocessing/preprocessing.py", line 120, in construct_corpus
    word_freq, doc_word_freq = load_data(corpus_path, recursive)
  File "/home/saria/Downloads/KATE-master/autoencoder/preprocessing/preprocessing.py", line 112, in load_data
    raise e
TypeError: 'errors' is an invalid keyword argument for this function

**Comment by hugochan** [comment]
It seems this exception was raised when calling the codecs.open function. Can you make sure that you can call this function successfully? codecs is a built-in module.

**Comment by saria85** [comment]
Yea Actually it can be run successfully.
